#pragma only_renderers d3d11
#pragma target 5.0

#pragma kernel RunDetailsPass

#include "../ChunkFunctions.hlsl"
#include "../Biome.hlsl"
#include "../ChunkColoring.hlsl"

/* Inputs */
StructuredBuffer<TriangleData> DetailTriangles;

/* Outputs */
RWStructuredBuffer<ChunkDetailData> DetailBuffer;

float3 BiomeMidColor(uint index)
{
    return Biomes[index].MidLight;
}

float4 SampleBiomeColor(float3 p)
{
    // Large-scale continent noise
    float continent = fbm2D(p.xz * 0.0005, 4);
    continent = continent * 0.5 + 0.5; // normalize to 0..1

    // Height bands (tune numbers freely)
    float oceanW = 1.0 - smoothstep(0.45, 0.50, continent);
    float landW = smoothstep(0.45, 0.55, continent);
    float mountainW = smoothstep(0.65, 0.75, continent);

    // Loud debug colors
    float3 oceanColor = Biomes[1].Mid; // blue
    float3 landColor = Biomes[3].Mid; // green
    float3 mountainColor = Biomes[5].Mid; // gray

    float3 color =
        oceanColor * oceanW +
        landColor * landW +
        mountainColor * mountainW;

    return float4(saturate(color), 1.0);
}

float4 DebugColorFromIndex(uint i)
{
    uint r = (i >> 0) & 0x3;
    uint g = (i >> 2) & 0x3;
    uint b = (i >> 4) & 0x3;

    float3 c = float3(r, g, b) / 3.0;
    return float4(c, 1);
}


[numthreads(64, 1, 1)]
void RunDetailsPass(uint3 id : SV_DispatchThreadID)
{
    TriangleData tri = DetailTriangles[id.x];
    ChunkDetailData d = (ChunkDetailData) 0;
    
    d.Biome = 0;
    //float4 debug = DebugColorFromIndex(tri.ChunkKeyIndex);
    
    d.ColorA = SampleBiomeColor(tri.a); //SampleBiomeBlend(Biomes[a], tri.a);
    d.ColorB = SampleBiomeColor(tri.b); //SampleBiomeBlend(Biomes[a], tri.a);
    d.ColorC = SampleBiomeColor(tri.c); //SampleBiomeBlend(Biomes[a], tri.a);

    DetailBuffer[id.x] = d;
}