#pragma kernel Generate

#include "Includes/PerlinNoise.hlsl"
#include "Includes/TriangleTable.hlsl"

struct ChunkInput
{
    float3 CoordPos;
    float3 WorldPos;
    int stepSize;
};

StructuredBuffer<ChunkInput> ChunkInputs;
RWStructuredBuffer<float> DensityMap;

int _SizeX;
int _SizeY;
int _SizeZ;

float _Seed;

float _ISOLevel;
float _ContinentFrequency;
float _ContinentAmplitude;
float _DetailFrequency;
float _DetailAmplitude;
float _FlatnessFrequency;
float _FlatnessStrength;
float _MountainFrequency;
float _MountainAmplitude;
float _MountainSharpness;
float _TotalHeightScale;

float GetDensityValue(float worldX, float worldY, float worldZ)
{
    float2 posXZ = float2(worldX, worldZ);

    float2 continentPos = posXZ * _ContinentFrequency;
    float continent = fbm2D(continentPos, 6);
    continent = smoothstep(0.0, 1.0, (continent + 1.0) * 0.5);

    float2 detailPos = (posXZ + 1234.0) * _DetailFrequency;
    float detail = fbm2D(detailPos, 6);

    float2 flatnessPos = (posXZ + 5555.0) * _FlatnessFrequency;
    float flatness = fbm2D(flatnessPos, 6);
    flatness = saturate((flatness + 1.0) * 0.5);
    flatness = pow(saturate(1.0 - flatness), _FlatnessStrength);

    float2 mountainMaskPos = (posXZ + 9999.0) * 0.001;
    float mountainMask = fbm2D(mountainMaskPos, 6);
    mountainMask = saturate((mountainMask + 1.0) * 0.5);
    float mountainWeight = smoothstep(0.85, 1.0, mountainMask);

    float2 mountainNoisePos = (posXZ + 999.0) * _MountainFrequency;
    float mountainNoise = fbm2D(mountainNoisePos, 6);
    mountainNoise = pow(max(mountainNoise, 0.0), _MountainSharpness) * mountainWeight;

    float rawHeight =
        continent * _ContinentAmplitude +
        detail * _DetailAmplitude * flatness +
        mountainNoise * _MountainAmplitude;

    float heightScale = max(_ContinentAmplitude + _MountainAmplitude, 0.0001);
    float normalized = rawHeight / heightScale;
    float finalHeight = normalized * _TotalHeightScale;

    float value = -(worldY - finalHeight);
    return (isnan(value) || isinf(value)) ? 0.0 : value;
}

[numthreads(1, 1, 1)]
void Generate(uint3 id : SV_DispatchThreadID)
{
    // total threads = dispatchX × dispatchY × dispatchZ

    int chunkSize = _SizeX; // = 17
    int voxelCount = chunkSize * chunkSize * chunkSize;

    int chunkIndex = id.x / chunkSize;
    int x = id.x % chunkSize;
    int y = id.y;
    int z = id.z;

    if (x >= _SizeX || y >= _SizeY || z >= _SizeZ)
        return;

    int index = chunkIndex * voxelCount + (x + y * _SizeX + z * _SizeX * _SizeY);
    ChunkInput chunk = ChunkInputs[chunkIndex];

    float3 worldPos = chunk.WorldPos + float3(x, y, z) * chunk.stepSize;
    worldPos.x += _Seed;
    worldPos.z += _Seed;

    DensityMap[index] = GetDensityValue(worldPos.x, worldPos.y, worldPos.z);
}
