namespace GingerVoxelSystem.Player
{
    using GingerVoxelSystem.Engine.Stage;
    using GingerVoxelSystem.Entity;
    using UnityEngine;

    /// <summary>
    /// Simple first-person style controller backed by a cached SDF collision volume.
    /// 
    /// This controller does not rely on Unity physics or mesh colliders. Instead,
    /// it queries a localized density block generated by <see cref="DensityCollisionStage"/>
    /// to resolve grounding against the terrain SDF.
    /// 
    /// The collision block is generated on the GPU only when needed and cached
    /// on the CPU for fast, per-frame sampling.
    /// </summary>
    [RequireComponent(typeof(SDFCapsuleCollider))]
    public class SdfPlayerController : MonoBehaviour
    {
        /// <summary>
        /// Helps with collisions on our fancy terrain.
        /// </summary>
        private SDFCapsuleCollider sdfCollider;

        /// <summary>
        /// Horizontal movement speed.
        /// </summary>
        public float moveSpeed = 6f;

        /// <summary>
        /// Downward acceleration applied when airborne.
        /// </summary>
        public float gravity = 20f;

        /// <summary>
        /// Upward velocity applied when jumping.
        /// </summary>
        public float jumpVelocity = 7f;

        /// <summary>
        /// The amount of available jumps.
        /// </summary>
        public int jumpCount = 2;

        /// <summary>
        /// The amount of remaining jumps.
        /// </summary>
        private int jumpsRemaining = 2;

        /// <summary>
        /// Helps with jumping to know whether we were grounded last update.
        /// </summary>
        private bool wasGrounded;

        /// <summary>
        /// Current velocity of the player.
        /// </summary>
        private Vector3 velocity;

        /// <summary>
        /// Initialize any related elements.
        /// </summary>
        private void Awake()
        {
            this.sdfCollider = GetComponent<SDFCapsuleCollider>();
        }

        /// <summary>
        /// Update the player movement.
        /// </summary>
        private void Update()
        {
            float dt = Time.deltaTime;

            ApplyMovement(dt);

            if (sdfCollider.CanResolve && sdfCollider.Grounded)
            {
                transform.position += Vector3.up * (sdfCollider.Radius - sdfCollider.LastGroundDistance);
                velocity.y = Mathf.Max(velocity.y, 0f);
            }
        }

        /// <summary>
        /// Applies basic first-person movement and gravity integration.
        /// Rotation is handled externally by the camera controller.
        /// </summary>
        private void ApplyMovement(float dt)
        {
            float h = Input.GetAxisRaw("Horizontal");
            float v = Input.GetAxisRaw("Vertical");

            Vector3 wish =
                transform.right * h +
                transform.forward * v;

            wish = Vector3.ClampMagnitude(wish, 1f);

            velocity.x = wish.x * moveSpeed;
            velocity.z = wish.z * moveSpeed;

            if (sdfCollider.Grounded && !wasGrounded)
            {
                jumpsRemaining = jumpCount;
            }

            // Jump input
            if (Input.GetKeyDown(KeyCode.Space) && jumpsRemaining > 0)
            {
                velocity.y = jumpVelocity;
                jumpsRemaining--;
            }

            if (!sdfCollider.Grounded)
            {
                velocity.y -= gravity * dt;
            }

            transform.position += velocity * dt;
            wasGrounded = sdfCollider.Grounded;
        }
    }
}
